apply from: "$rootDir/buildSrc/androidApp.gradle"

android {
    namespace 'net.maxsmr.permissionchecker.test'
}

dependencies {
    implementation project(':permissionchecker')
//    implementation "net.maxsmr:permissionchecker:${project.getModuleVersionNameByPath(":permissionchecker")}"

    api "androidx.appcompat:appcompat:$androidxAppCompatVersion"
}
