apply from: "$rootDir/buildSrc/config.gradle"
apply from: "$rootDir/buildSrc/buildUtils.gradle"

apply plugin: 'java-library'
apply plugin: 'kotlin'

version = project.getModuleVersionNameByPath(project.path)
archivesBaseName = "${moduleInfo.id}+${moduleInfo.versionName}"

java {
    sourceCompatibility = sourceCompatibilityVersion
    targetCompatibility = sourceCompatibilityVersion
}

task sourcesJar(type: Jar) {
    archiveClassifier  = 'sources'
    from java.sourceSets.main.java.srcDirs
}

artifacts {
    archives sourcesJar
}

dependencies {
    api fileTree(dir: 'libs', include: ['*.jar'])

    // Jetbrains annotations
    implementation "org.jetbrains:annotations:$jetbrainsAnnotationsVersion"
}